version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test

workflows:
  version: 2
  instal_and_test:
    jobs:
      - test:
        filters:
          branches:
            only: master
